FROM php:8.4-fpm

RUN apt-get update && apt-get install -y \
    git curl unzip libpng-dev libonig-dev libxml2-dev

RUN docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

RUN echo "opcache.enable=0\nopcache.enable_cli=0" \
    > /usr/local/etc/php/conf.d/opcache-dev.ini

WORKDIR /var/www

COPY composer.json composer.lock ./

EXPOSE 8002

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8002"]
